export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE';
export const LOAD_MOVIES_LOADING = 'LOAD_MOVIES_LOADING';
export const SORT_BY = 'SORT_BY';
export const FILTER_TEXT = 'FILTER_TEXT';
export const SEARCH_BY = 'SEARCH_BY';